#pragma once


#define MAIN_DLG_WIDTH 1280 
#define MAIN_DLG_HEIGHT 800

#define IMAGE_DLG_WIDTH MAIN_DLG_WIDTH
#define IMAGE_DLG_HEIGHT MAIN_DLG_HEIGHT-80

#define IMAGE_BPP 8

#define SAFE_DELETE_PTR(x) if(x)delete x;x=nullptr

#define IMAGE_DATA_RESET_VALUE 0X00

#define IMAGE_DATA_SET_VALUE 0XFF

#define RGB_CLR_TBL_SIZE_BPP_8 256

#define POINT_CNT 3

#define CIRCLE_RADIUS 10
#define CIRCLE_RADIUS_MIN 5
#define CIRCLE_RADIUS_MAX 20

#define OUTER_CIRCLE_LINE_SIZE 2
#define OUTER_CIRCLE_LINE_SIZE_MIN 1
#define OUTER_CIRCLE_LINE_SIZE_MAX 10

#define INVALID_SEL_PT_IDX 7777

#define IMAGE_DLG_ERASE_BK_CLR RGB(0,0,0)
